### PR TITLE
fix variables' name

### PR DESCRIPTION
**Pull request by freedeaths**
## Why are these changes needed?

Make variable names human-friendly

## Related issue number

None

## Checks

- [ ] I've included any doc changes needed for https://github.com/pingcap/LinguFlow/.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by freedeaths** [comment]
@lucklove @lilyjazz PTAL

**Comment by freedeaths** [comment]
@lucklove @lilyjazz PTAL

**Review by abcdabcd3899 — APPROVED** [review]
LGTM

**Review by lilyjazz — APPROVED** [review]
LGTM to use `search_engine_id` instead of `google_search_id`

**Pull request merged**
